"""detection areas 2

Revision ID: 04ceff8f177c
Revises: 127327943bb9
Create Date: 2021-12-08 12:50:19.222460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04ceff8f177c'
down_revision = '127327943bb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detection_areas', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'detection_areas', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detection_areas', type_='foreignkey')
    op.drop_column('detection_areas', 'user_id')
    # ### end Alembic commands ###
