"""empty message

Revision ID: 0e2947cabe98
Revises: 52cf95c88d21
Create Date: 2021-12-06 12:39:33.759757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e2947cabe98'
down_revision = '52cf95c88d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('causes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cause_type', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('causes')
    # ### end Alembic commands ###
