"""detection areas

Revision ID: 127327943bb9
Revises: 626be6c0d21e
Create Date: 2021-12-08 12:49:34.935000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '127327943bb9'
down_revision = '626be6c0d21e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detection_area', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detection_areas')
    # ### end Alembic commands ###
