"""empty message

Revision ID: 21e7e2bab200
Revises: e0d5cb92baa0
Create Date: 2021-12-01 14:21:43.753185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21e7e2bab200'
down_revision = 'e0d5cb92baa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('in_com', sa.Column('order_number', sa.String(length=140), nullable=True))
    op.drop_constraint(None, 'in_com', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'in_com', 'user', ['user_id'], ['id'])
    op.drop_column('in_com', 'order_number')
    # ### end Alembic commands ###
