"""empty message

Revision ID: 336eac70887b
Revises: 21e7e2bab200
Create Date: 2021-12-06 10:22:40.663841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '336eac70887b'
down_revision = '21e7e2bab200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_model', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_types', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('types')
    op.drop_table('models')
    # ### end Alembic commands ###
