"""empty message

Revision ID: 52cf95c88d21
Revises: 336eac70887b
Create Date: 2021-12-06 10:29:16.792960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52cf95c88d21'
down_revision = '336eac70887b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('types', sa.Column('product_type', sa.String(length=140), nullable=True))
    op.drop_column('types', 'product_types')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('types', sa.Column('product_types', sa.VARCHAR(length=140), nullable=True))
    op.drop_column('types', 'product_type')
    # ### end Alembic commands ###
