"""empty message

Revision ID: 5e7e733ef119
Revises: 233117c8f49c
Create Date: 2021-12-01 11:42:10.837798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e7e733ef119'
down_revision = '233117c8f49c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'in_com', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'in_com', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
