"""empty message

Revision ID: 626be6c0d21e
Revises: 0e2947cabe98
Create Date: 2021-12-06 14:06:51.406230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '626be6c0d21e'
down_revision = '0e2947cabe98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('in_com', sa.Column('registration_status', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('in_com', 'registration_status')
    # ### end Alembic commands ###
