"""empty message

Revision ID: db344b13a55a
Revises: d012ad8445df
Create Date: 2021-12-10 14:11:27.149940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db344b13a55a'
down_revision = 'd012ad8445df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'detection_areas', 'user', ['user_id'], ['id'])
    op.add_column('in_com', sa.Column('complaint_status', sa.String(length=140), nullable=True))
    op.drop_column('in_com', 'registration_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('in_com', sa.Column('registration_status', sa.VARCHAR(length=140), nullable=True))
    op.drop_column('in_com', 'complaint_status')
    op.drop_constraint(None, 'detection_areas', type_='foreignkey')
    # ### end Alembic commands ###
