"""detection areas 2

Revision ID: fd2f1f34973f
Revises: 04ceff8f177c
Create Date: 2021-12-08 12:51:23.980179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd2f1f34973f'
down_revision = '04ceff8f177c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'detection_areas', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detection_areas', type_='foreignkey')
    # ### end Alembic commands ###
